### ISSUE TITLE
Implement `absent` flag to indicate teams that are not there

### ISSUE THREAD

**Issue by htoo97** [UCSDTESC/gavel#4]
Some teams usually submit on devpost and decide to no longer stay for the expo judging. When that happens, those teams get repeatedly skipped by judges, but they still keep getting re-prioritized due to the way team assignment works. We also do not want to get rid of the `Skip` button, as it has certain use cases:

- Conflict of interest, such as the judge being close friends with the team being judged
- Another judge already in the middle of judging the team

We want a new `Not There` button instead. When pressed, it should increment the `absent` count on the team. To implement this:
- [x] Create new table that forms a many-to-many relationship between items (teams) and annotators (judges) and stores any time a judge clicks "not there" for a team. (@htoo97)
- [x] #1: Modify `/admin` view to show the `absent` count (@vickivc )
- [x] #2: Add "Not there" button (@michl1001)
- [x] #3: Increment absent count (@vickivc)
- [ ] #10: Automatically deactivate team if their absent count exceeds threshold (@ayushiatsharma )
(Note: I'll add you to the tesc org later and then assign the issues to them formally later. You can start working on it!)

**Comment by htoo97** [comment]
Btw go check out my commit ffc5e205a for more info on how I set up the model.
